kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubemove
subjects:
- kind: ServiceAccount
  name: kubemove
roleRef:
  kind: Role
  name: kubemove
  apiGroup: rbac.authorization.k8s.io
